const stateOrder=["authorized_advisory_received","proposals_ready","instructions_delivered","responses_in_progress","resource_conflict","allocation_approved","response_verified","closed"];
const actions={authorized_advisory_received:{label:"Resume governed automation",note:"Activates the registered fleet from the authorized feed.",endpoint:"autopilot"},proposals_ready:{label:"Resume governed automation",note:"Applies the pre-authorized standing playbook and delivery policy.",endpoint:"autopilot"},instructions_delivered:{label:"Receive facility updates",note:"Creates evidence, a request for help, and one missing acknowledgement.",endpoint:"facility-updates"},responses_in_progress:{label:"Resume governed automation",note:"Surfaces competing requests without choosing a winner.",endpoint:"autopilot"},resource_conflict:{label:"Allocate as incident commander",note:"A named synthetic official chooses one supported option.",endpoint:"allocate"},allocation_approved:{label:"Resume governed automation",note:"Routes the missed acknowledgement without another operator step.",endpoint:"autopilot"},response_verified:{label:"Apply authorized rescission",note:"Runs differentiated recovery checks after a human rescission.",endpoint:"recover"},closed:{label:"Incident closed",note:"Reset to replay the full synthetic response.",endpoint:null}};
let incident=null,auto=false;const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const escapeHtml=v=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);
function setTheme(t){document.documentElement.dataset.theme=t;localStorage.setItem("one-advisory-theme",t);const dark=t==="dark";$("#theme-toggle").setAttribute("aria-pressed",String(dark));$("#theme-toggle b").textContent=dark?"Dark":"Light"}
function toast(m){const n=$("#toast");n.textContent=m;n.classList.add("show");setTimeout(()=>n.classList.remove("show"),2400)}
async function api(path,options={}){const r=await fetch(path,{headers:{"Content-Type":"application/json"},...options});if(!r.ok){const e=await r.json().catch(()=>({detail:"Request failed"}));throw new Error(e.detail)}return r.json()}
function stateName(s){return({authorized_advisory_received:"Authorized advisory received",proposals_ready:"Facility proposals ready",instructions_delivered:"Approved instructions delivered",responses_in_progress:"Facility responses in progress",resource_conflict:"Resource conflict needs authority",allocation_approved:"Allocation approved by human",response_verified:"Active response verified",closed:"Recovery complete"})[s]||s.replaceAll("_"," ")}
function renderFacilities(rows){$("#facility-list").innerHTML=rows.map(f=>{const done=f.tasks.filter(t=>["evidenced","acknowledged"].includes(t.status)).length;const letter=f.type==="dialysis"?"D":f.type==="school_childcare"?"S":"C";return `<article class="facility-row"><div class="facility-identity"><span class="facility-letter">${letter}</span><div><b>${escapeHtml(f.name)}</b><small>${escapeHtml(f.type.replaceAll("_"," "))} · ${f.tasks.length} sourced tasks</small></div></div><span class="state-pill ${f.response_state}">${escapeHtml(f.response_state.replaceAll("_"," "))}</span><div class="task-meter"><span>${done}/${f.tasks.length}</span><i style="--progress:${done/f.tasks.length*100}%"></i></div></article>`}).join("");
 const cls=s=>s==="escalated"||s==="no_response"?"risk":s==="assistance_requested"||s==="proposal_ready"?"wait":"";$("#map-markers").innerHTML=rows.map(f=>`<g class="ops-marker ${cls(f.response_state)}" transform="translate(${f.coordinates.x*7} ${f.coordinates.y*6})"><circle r="22"/><text text-anchor="middle" y="4">${f.type==="dialysis"?"D":f.type==="school_childcare"?"S":"C"}</text></g>`).join("")}
function renderConflict(c){$("#conflict-badge").textContent=c?"1":"0";if(!c){$("#conflict-panel").className="empty-state";$("#conflict-panel").innerHTML="<span></span><h3>No resource conflict yet</h3><p>The fleet will surface competing requests without allocating on its own.</p>";return}$("#conflict-panel").className="conflict-card";$("#conflict-panel").innerHTML=`<span class="conflict-label">${escapeHtml(c.status.replaceAll("_"," "))}</span><h3>${escapeHtml(c.resource)}</h3><div class="request-pair">${c.requests.map(r=>`<div><b>${r.facility_id==="fac-dialysis"?"Harbor Dialysis":"Cedar House Care"}</b><span>${escapeHtml(r.reason)}</span></div>`).join("")}</div><div class="no-auto">AI allocation: NONE · ${c.selected?`Human selected ${escapeHtml(c.selected)}`:"Human decision required"}</div>`}
function renderTimeline(rows){$("#timeline").innerHTML=[...rows].reverse().map(r=>`<article class="trace-item ${r.status}"><span class="trace-dot"></span><div class="trace-copy"><div class="trace-meta"><b>${escapeHtml(r.actor)}</b><time>${new Date(r.at).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</time></div><h4>${escapeHtml(r.action)}</h4><p>${escapeHtml(r.detail)}</p>${r.evidence_ids.length?`<small>${r.evidence_ids.length} evidence link${r.evidence_ids.length>1?"s":""}</small>`:""}</div></article>`).join("")}
function renderPhases(s){const idx=stateOrder.indexOf(s);$$("#phases li").forEach((li,i)=>{li.classList.toggle("done",i<idx||s==="closed");li.classList.toggle("active",i===idx&&s!=="closed")})}
function renderAutonomy(a={}){const rows=a.last_run_actions||[],wait=String(a.current_wait||"none").replaceAll("_"," ");$("#autonomy-receipt").dataset.complete=String(Boolean(a.complete));$("#autonomy-title").textContent=a.complete?"Fleet run closed":rows.length?"Governed operations resumed":"Holding for a real event";$("#autonomy-trigger").textContent=a.trigger||"Authorized advisory";$("#autonomy-actions").textContent=rows.length+" this run";$("#autonomy-wait").textContent=a.complete?"Recovery verified":wait}
function render(data){incident=data;renderAutonomy(data.autonomy);$("#state-title").textContent=stateName(data.status);$("#incident-id").textContent=`${data.incident_id} · synthetic tabletop`;$("#state-light").className=data.status==="resource_conflict"?"wait":"";$("#facility-count").textContent=data.metrics.affected_facilities;$("#task-count").textContent=data.metrics.source_backed_tasks;$("#rejection-count").textContent=data.metrics.policy_rejections;renderFacilities(data.facilities);renderConflict(data.resource_conflict);renderTimeline(data.timeline);renderPhases(data.status);const a=actions[data.status];$("#advance").textContent=a.label;$("#advance").disabled=!a.endpoint||auto;$("#next-note").textContent=a.note}
async function reset(){try{render(await api("/api/incidents",{method:"POST"}));toast("New synthetic sample loaded")}catch(e){toast(e.message)}}
async function advance(){if(!incident)return;const a=actions[incident.status];if(!a.endpoint)return;$(".command").setAttribute("aria-busy","true");try{let options={method:"POST"};if(a.endpoint==="approve"){await api(`/api/incidents/${incident.incident_id}/policy-test`,{method:"POST"});options.body=JSON.stringify({approver:"Jordan Lee, incident commander — synthetic"})}if(a.endpoint==="allocate")options.body=JSON.stringify({option_id:"slot-to-ltc",approver:"Jordan Lee, incident commander — synthetic"});if(a.endpoint==="recover")options.body=JSON.stringify({approver:"Jordan Lee, incident commander — synthetic"});render(await api(`/api/incidents/${incident.incident_id}/${a.endpoint}`,options));if(incident.status==="resource_conflict"){$$("[role=tab]").find(t=>t.dataset.tab==="conflict").click()}toast(stateName(incident.status))}catch(e){toast(e.message)}finally{$(".command").setAttribute("aria-busy","false")}}
async function runAll(){if(auto)return;auto=true;$("#autorun").disabled=true;$(".command").setAttribute("aria-busy","true");try{const completed=await api("/api/demo/full",{method:"POST"});render(completed);toast("One trigger completed the governed response")}catch(error){toast(error.message)}finally{auto=false;$("#autorun").disabled=false;$(".command").setAttribute("aria-busy","false")}}
function tabs(){$$("[role=tab]").forEach(tab=>tab.addEventListener("click",()=>{$$("[role=tab]").forEach(t=>t.setAttribute("aria-selected",String(t===tab)));$$(".ops-view").forEach(v=>v.hidden=v.id!==`view-${tab.dataset.tab}`)}))}
document.addEventListener("DOMContentLoaded",async()=>{setTheme(localStorage.getItem("one-advisory-theme")||"dark");$("#theme-toggle").addEventListener("click",()=>setTheme(document.documentElement.dataset.theme==="dark"?"light":"dark"));$("#advance").addEventListener("click",advance);$("#reset").addEventListener("click",reset);$("#autorun").addEventListener("click",runAll);tabs()});

